//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.93")]
public enum mtx_IncrementNumberState
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// 
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("mtx_incrementnumber")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.93")]
public partial class mtx_IncrementNumber : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public mtx_IncrementNumber() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "mtx_incrementnumber";
	
	public const string EntityLogicalCollectionName = "mtx_incrementnumbers";
	
	public const string EntitySetName = "mtx_incrementnumbers";
	
	public const int EntityTypeCode = 10380;
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של המשתמש שיצר את הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// התאריך והשעה שבהם נוצרה הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של המשתמש הנציג שיצר את הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// מספר הרצף של הייבוא שיצר רשומה זו.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של המשתמש ששינה את הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// התאריך והשעה שבהם השתנתה הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של המשתמש הנציג ששינה את הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_incrementingnumberint")]
	public System.Nullable<int> mtx_IncrementingNumberInt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("mtx_incrementingnumberint");
		}
		set
		{
			this.OnPropertyChanging("mtx_IncrementingNumberInt");
			this.SetAttributeValue("mtx_incrementingnumberint", value);
			this.OnPropertyChanged("mtx_IncrementingNumberInt");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של מופעי ישות
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_incrementnumberid")]
	public System.Nullable<System.Guid> mtx_IncrementNumberId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("mtx_incrementnumberid");
		}
		set
		{
			this.OnPropertyChanging("mtx_IncrementNumberId");
			this.SetAttributeValue("mtx_incrementnumberid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("mtx_IncrementNumberId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_incrementnumberid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.mtx_IncrementNumberId = value;
		}
	}
	
	/// <summary>
	/// שם הישות המותאמת אישית.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_name")]
	public string mtx_name
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_name");
		}
		set
		{
			this.OnPropertyChanging("mtx_name");
			this.SetAttributeValue("mtx_name", value);
			this.OnPropertyChanged("mtx_name");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_objectivecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue mtx_ObjectiveCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mtx_objectivecode");
		}
		set
		{
			this.OnPropertyChanging("mtx_ObjectiveCode");
			this.SetAttributeValue("mtx_objectivecode", value);
			this.OnPropertyChanged("mtx_ObjectiveCode");
		}
	}
	
	/// <summary>
	/// התאריך והשעה שבהם הועברה הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// מזהה בעלים
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של היחידה העסקית שהרשומה נמצאת בבעלותה
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// ‏‏ה‏‏מזהה הייחודי של הצוות שהרשומה נמצאת בבעלותו.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של המשתמש שהרשומה נמצאת בבעלותו.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// מצב המספר תוספת אוטומטית
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public System.Nullable<mtx_IncrementNumberState> statecode
	{
		get
		{
			Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
			if ((optionSet != null))
			{
				return ((mtx_IncrementNumberState)(System.Enum.ToObject(typeof(mtx_IncrementNumberState), optionSet.Value)));
			}
			else
			{
				return null;
			}
		}
		set
		{
			this.OnPropertyChanging("statecode");
			if ((value == null))
			{
				this.SetAttributeValue("statecode", null);
			}
			else
			{
				this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
			}
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// הסיבה למצב של המספר תוספת אוטומטית
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statuscode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// ‏‏לשימוש פנימי בלבד.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// ‏‏קוד אזור הזמן שהיה בשימוש בעת יצירת הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// מספר גירסה
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
}
